#!/usr/bin/env python3
"""
تحويل الكوكيز من JSON إلى Netscape format
"""

cookies_json = [
    {"domain": ".youtube.com", "expirationDate": 1777268242.937281, "httpOnly": True, "name": "VISITOR_PRIVACY_METADATA", "path": "/", "secure": True, "value": "CgJKTxIEGgAgFQ%3D%3D"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.179211, "httpOnly": True, "name": "__Secure-3PSID", "path": "/", "secure": True, "value": "g.a0002wijnn7eCa8Coo388wOGyPF8ZnCj38cTRBgcOmIawk2J2EQdxaAKj68NmCFu7g24pb97RAACgYKAWoSARISFQHGX2MivWYWEHWcN3YDKvnnXA7RXRoVAUF8yKp6x4HZ-UTAuPjGnbOgru2f0076"},
    {"domain": ".youtube.com", "expirationDate": 1761718020.827531, "httpOnly": True, "name": "GPS", "path": "/", "secure": True, "value": "1"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.178747, "httpOnly": True, "name": "__Secure-1PSIDTS", "path": "/", "secure": True, "value": "sidts-CjUBwQ9iI4aK9dxH2FFC2elo43tBOnAkGQ-RR-mnEU6JRM7yBS7aTC7gdN5bTvVVjvdzmDgKKRAA"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.179018, "httpOnly": False, "name": "SAPISID", "path": "/", "secure": True, "value": "4UV6sbTx5YlJps54/AZ4uU2UVr-cBAtfnf"},
    {"domain": ".youtube.com", "expirationDate": 1777268242.937497, "httpOnly": True, "name": "__Secure-1PSIDCC", "path": "/", "secure": True, "value": "AKEyXzUn2rxhAyZnN3dQ3SuxRTuyR2rVrZahdd8WINA9nobsw5wghLXHRA1ANwLFcu_-OM3gYQ"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.178953, "httpOnly": True, "name": "SSID", "path": "/", "secure": True, "value": "A54G3IMaffzgN2ogp"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.179051, "httpOnly": False, "name": "__Secure-1PAPISID", "path": "/", "secure": True, "value": "4UV6sbTx5YlJps54/AZ4uU2UVr-cBAtfnf"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.179179, "httpOnly": True, "name": "__Secure-1PSID", "path": "/", "secure": True, "value": "g.a0002wijnn7eCa8Coo388wOGyPF8ZnCj38cTRBgcOmIawk2J2EQd7esK3GeEZMOOjibeJy1Y_gACgYKASQSARISFQHGX2Mi7B0o-1G-dx6hyzFCqx5nQBoVAUF8yKqQTRuGNUYcPpgC4sJlRYsX0076"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.179107, "httpOnly": False, "name": "__Secure-3PAPISID", "path": "/", "secure": True, "value": "4UV6sbTx5YlJps54/AZ4uU2UVr-cBAtfnf"},
    {"domain": ".youtube.com", "expirationDate": 1777268242.937577, "httpOnly": True, "name": "__Secure-3PSIDCC", "path": "/", "secure": True, "value": "AKEyXzUgxAlJdkXD0dSvmNsp9X5XNwf4KtREWSWxunPQ3Xv2jKrALtpC0lXCGmVVkLKDg7rdcQ"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.178852, "httpOnly": True, "name": "__Secure-3PSIDTS", "path": "/", "secure": True, "value": "sidts-CjUBwQ9iI4aK9dxH2FFC2elo43tBOnAkGQ-RR-mnEU6JRM7yBS7aTC7gdN5bTvVVjvdzmDgKKRAA"},
    {"domain": ".youtube.com", "expirationDate": 1777268230.438483, "httpOnly": True, "name": "LOGIN_INFO", "path": "/", "secure": True, "value": "AFmmF2swRQIhAKw6ELdRMRU6N0iGzW-N2Pw5xX1BKP8JjubZFZGy4-ifAiBW8jtumtsS6TJTmcDTGmsRAQdKajQrJWQKCEs1ExKZcA:QUQ3MjNmeDZIWjFBTTdEV2pxcDVOQ3BBTUdKRWo2Q09QRTV4SVpMNWpUSkFxZllYY0JjOUVzalpTRjI0QnoxMTY2ZU9MX3hEQkpuMURhcHVaRElTcS1QbjBlNHdaZ2JSVEpvaElPLVVJNG1ud3NwSVdGbk1oenhoZG1nSzU0TWtDai04WXQ1dkc4Y0NQYXoyQjE3dEVHejRnZlFvdm40NUVB"},
    {"domain": ".youtube.com", "expirationDate": 1777268237.972544, "httpOnly": False, "name": "PREF", "path": "/", "secure": True, "value": "f4=4000000&f6=40000000&tz=Asia.Amman&f5=30000"},
    {"domain": ".youtube.com", "expirationDate": 1777268242.937087, "httpOnly": True, "name": "VISITOR_INFO1_LIVE", "path": "/", "secure": True, "value": "_o7N4Bl57WQ"}
]

# تحويل إلى Netscape format
lines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by Export Cookies extension for Chrome",
    ""
]

for c in cookies_json:
    domain = c["domain"]
    flag = "TRUE"
    path = c["path"]
    secure = "TRUE" if c.get("secure") else "FALSE"
    expiration = str(int(c.get("expirationDate", 0)))
    name = c["name"]
    value = c["value"]
    
    line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
    lines.append(line)

# حفظ في secrets/cookies.txt
output_file = "secrets/cookies.txt"
with open(output_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"✅ Cookies saved to {output_file}")
print(f"📊 Total cookies: {len(cookies_json)}")
print(f"📅 Expiration: Until 2026-04-24 (16+ months)")
